modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="life_contract"
version="1.0.0"
displayName="Life Contract"
description="Connects your soul to other mods."
authors="Alku"

[[mixins]]
config="life_contract.mixins.json"

[[dependencies.life_contract]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.life_contract]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.life_contract]]
modId="ldlib2"
mandatory=true
versionRange="[2.2.27,)"
ordering="AFTER"
side="CLIENT"
[[dependencies.life_contract]]
modId="geckolib"
mandatory=true
versionRange="[4.4,)"
ordering="AFTER"
side="BOTH"
[[dependencies.life_contract]]
modId="spore"
mandatory=false
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.life_contract]]
modId="airdrop"
mandatory=false
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.life_contract]]
modId="borderweaver"
mandatory=false
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.life_contract]]
modId="caerula_arbor"
mandatory=false
versionRange="[0.11.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies.life_contract]]
modId="xaerominimap"
mandatory=false
versionRange="[26.2,)"
ordering="AFTER"
side="CLIENT"
